# Generated by Django 5.1.1 on 2024-09-30 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0002_alter_mailing_options_alter_mailing_start_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='attempt_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время попытки отправки рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время первой рассылки'),
        ),
    ]
